laboratory-for-translational-medicine/SlicerCineTrack

Track/Track.py
This PR replaces `time.sleep()` with a QTTimer. This allows the GUI to be interactive during the pause/delay. This hopes to close https://github.com/laboratory-for-translational-medicine/SlicerTrack/issues/32.
Ubuntu
Windows
=> [SlicerTrack][Logic] Use QTTimer to improve interactivity during delay

Track/Track.py
The purpose of this PR is to make a label map of our 3D segmentation and to use this as the "label layer" in the slice view. This label map acts as a better mask of the 3D segmentation to overlay on the 2D images. This label map only covers the exact ROI area (while the 3D volume would darken the surrounding) and also provides some useful features (such as being able to view the mask either as a filled region vs. an outline).
Ubuntu
=> [SlicerTrack][Logic] Use label map of 3D segmentation as a better mask to overlay on the 2D images

Track/Track.py
When the module is reloaded (i.e. the module is destroyed and then recreated while being provided the same parameter node) an error would appear that would indicate the `totalImages` variable was `None`. This was because after the module was re-created, `totalImages` was given it's default value (`None`) and it was never set to the number of images within the 2D images virtual folder.
This PR fixes the bug by setting the `totalImages` var in the `setParameterNode()` function, which is called after the module is created. If it finds the 2D images folder in the provided parameter node, it will set the `totalImages` variable accordingly.
Ubuntu
Windows
=> [SlicerTrack] Fix module reload bug

Track/Track.py
This PR enables the use of the FPS input box so that it can affect the delay that occurs between each frame/step in the sequence.
Ex. If the FPS is 4, the delay will be 1000 ms / 4 = 250 ms (each frame/step will wait 250ms before moving to the next)
Ubuntu
Windows
=> [SlicerTrack][Logic] Enable FPS input to change the delay between each step/frame

Track/Track.py
When using the SlicerTrack extension loading the 2D images and the transformation data from the transforms file can take a bit of time, and the GUI is frozen while this is happening. This slowness is exacerbated on slower systems.
This PR implements a progress bar dialog which is shown at these importation steps. The bar allows the user to anticipate how much longer it will take to load the data into 3D Slicer.
This PR intends to close https://github.com/laboratory-for-translational-medicine/SlicerTrack/issues/34
Ubuntu
Windows
=> [SlicerTrack] Implement loading/progress bar for images/transformation data importation

Track/Track.py
This PR changes the overlay of the label map from being shown as a filled region to an outline only.
It also makes the opacity of the overlay stronger (default = no opacity, solid fill).
Ubuntu
=> [SlicerTrack][Logic] Show outline only of 3D segmentation label map in slice views

Track/Track.py
The purpose of this PR is to add two new GUI widgets. The first is for switched between whether the label map layer overlay is outlined or filled, and the second is a slider control for changing the opacity of the label map layer.
Tested on Ubuntu
=> [SlicerTrack][GUI] Add visual controls for opacity and overlay outline/fill switching

Track/Track.py
This PR replaces our FPS input box with a playback speed input box. The motivation for this PR was to simplify how the user makes the playback slower or faster, and to not have them concerned with the precise amount of frames per second (FPS). It is also difficult to guarantee that the playback will be playing at exactly a particular FPS value.
We also update the visuals for some other controls as well so that they are more or less consistent with each other.
Tested on Ubuntu
=> [GUI] Implement playback speed multiplier control

Track/Track.py
Previously we were only using Sagittal and Coronal 2D images with SlicerTrack. Since we now have Axial images available, this PR enables their usage with the extension.
Tested on Ubuntu
=> [Logic] Enable usage of axial images with SlicerTrack

Track/Track.py
This PR removes the use of the `progressCount` accumulator variable from the `createTransformNodesFromTransformData()` and `loadImagesIntoVirtualFolder()` functions, and replaces it with for loop variables that were already in use in this codebase.
This PR intends to close #67 
MacOS (Version 5.2.2 - Stable Release)
=> [Logic][NFC] Modify looping statements to simplify code

Track/Track.py
The overlay on 2D images are cleared when resetState() is called.
This PR intends to close #60
MacOS (Version 5.2.2 - Stable Release and Version 5.3.0 - Preview Release)
=> [SlicerTrack][Logic] Clear Overlay on the 2D images

Track/Track.py
The purpose of this PR is to:
- Implement the usage of the Custom Parameter Node
- Move missing state variables into parameter node
- Move certain function to and from the Logic to better align with the 3D Slicer architecture
This PR also does the following:
- Improves our usage of `updateGUIFromParameterNode()`
- Simplify and rename `resetState()` function into `resetVisuals()`
- The state is now appropriately reset within `updateParameterNodeFromGUI()`
- Implements the usage of `setDefaultParameters()`
We try to update the GUI within `updateGUIFromParameterNode()` according to our state variables within the parameter node.
This PR should resolve https://github.com/laboratory-for-translational-medicine/SlicerTrack/issues/72 and https://github.com/laboratory-for-translational-medicine/Slic …
=> [Logic][Parameter Node] Implement custom parameter node

Track/Track.py
The purpose of this PR is to implement the usage of `Sequence` and `SequenceBrowser` nodes in the backend of SlicerTrack.
We also hookup the Sequence Browser operation with the media player GUI buttons. This simplifies our code in a lot of places.
This should resolve https://github.com/laboratory-for-translational-medicine/SlicerTrack/issues/62
Note: We no longer visualize the 2D images and 3D segmentation in the 3D view due to slowness during playback at higher speeds. I have left the code for this functionality commented out.
NOTE: This change may crash 3D Slicer for you when using it alongside the `Sequences` module, if you are not using the latest preview release.
=> [Logic][Parameter Node] Integrate Sequence and SequenceBrowser nodes into backend

Track/Track.py
This PR relocates the initialization of the `LPSToRASMatrix` variable from within the loop to before the loop begins. This change allows the variable to be defined before the start of the loop.
This PR intends to close #88 
Tested on MacOS (Version 5.3.0 - Preview Release)
=> [Logic][NFC] Move `LPStoRASMatrix` outside the loop

Track/Track.py
This PR intends to accept different Transforms filetypes in the "Inputs" section of our extension. The Transforms File would accept filetypes of .csv .xls .xlsx .txt
Tested on MacOS (Version 5.3.0 - Preview Release)
=> Remove filename restrictions for Transforms Files and support multiple extensions

Track/Track.py
-  Update the displayed image when the slider under 'sequence' is moved, either by dragging the slider or clicking on the slider
- Update the displayed image when the arrow buttons are pressed on the spinbox containing the current image number
Tested on MacOS (Version 5.4.0 - Stable Release)
=> Update displayed image when sequence slider moved

Track/Track.py
This PR includes the following changes:
- Adjusted the playback speed value to match `n` frames per second when set to `n` fps.
- Disabled the "Apply Transformation" button after a transformation is applied and re-enabled the button when no transforms have been applied to its corresponding 2D Cine Images.
- Added a "Transformation Applied" text to confirm to the user that the transformation has been applied. This is done because the user can apply a transformation without a segmentation, and won't visually see the Transformations being loaded.
- Removed redundant code responsible for enabling Qt objects.
- Tested on MacOS (Version 5.4.0 - Stable Release)
=> Behavior Adjustments for FPS, Spinbox, and ApplyTransformation

Track/Track.py
This PR intends to make the following change:
- Fix image skipping bug when increasing playback speed while playing sequence
Tested on Windows 10 (Version 5.4.0 - Stable Release)
=> Resolve image skipping bug when increasing playback speed while playing sequence

Track/Track.py
This PR intends to add a "Help & Acknowledgment" section to SlicerTrack, which includes a description to the extension, link to the website (https://slicertrack.github.io/), acknowledgments, and contributors to SlicerTrack.
This section appears on all other extensions available on 3D Slicer.
=> Add a "Help & Acknowledgment" section to the extension

Track/utils/TrackLogic.py
-  Fixed error message when there are mistakes/errors (eg. punctuation, letters, etc) in the transforms file
Tested on Windows (Version 5.6.0 - Stable Release)
=> Fixed transforms file error message

Track/Track.py
- Created tooltip for stop sequence button letting the user know that clicking it will take the slider back to Image 1
- Removed "2D" from Cine Images Folder input & "3D" from Segmentation File Input
Tested on MacOS (Version 5.6.0 - Stable Release)
=> Added tooltip for stop button

Track/utils/TrackLogic.py
###Description
Add support for loading Cine Images in Dicom (.dcm) format
=> Add support for .dcm images

Track/Track.py
Tested on Mac, Slicer 5.6.1 stable
After click apply, the button greyed out
If User change 1 of the 3 column selector, the button is enable again, and the text "Transformation Applied" is hidden.
From here, user can click Apply again and continue to view the sequence.
=> Keep apply button enable after clicked

Track/Track.py
Changed Reset Button so that it only applies to SlicerTrack, and not inputs loaded from other extensions.
Tested on Windows(Slicer Version 5.6.1)
=> Fix Reset Button functionality

Track/Track.py, Track/utils/TrackLogic.py
This PR intends to make the following change:
- Fixed the bug occurring when the user actively already has a dataset playing with SlicerTrack, and tries to reupload new Cine Images or a new Segmentation file
- Fixed the bug occurring while the user tries to delete any of the files uploaded into SlicerTrack while the sequence is actively playing
Tested on MacOS (Version 5.6.1 - Stable Release)
=> Bug fix reuploading files when active sequence

Track/Track.py
- Allows for the user to upload a new transforms file while the sequence is active with another data set
=> Bug fix reuploading transforms file in sequence

Track/Track.py
- When selecting SlicerTrack in the drop-down menu, it will now say SlicerTrack instead of Tracking
=> Drop Down Menu Change

README.md
Update Readme.md file base on this comment https://github.com/Slicer/ExtensionsIndex/pull/2030#issuecomment-2103751830
1. Add a gif to show what the extension can do
2. Add sample datasets
3. Upload Directory Tree
4. Fix markdown styling
=> Update Readme: Add gif, tutorial, sample datasets

README.md
A quick fix to a broken link, where the `Data.zip` file was not being downloaded from the link provided to `Dataset 1` in the README.
=> Update README.md - Fix Link

Track/Track.py
This PR intends to change the functionality of the 3D segmentation to ensure that only binary 3D images can be used as a segmentation. 
Tested with Slicer 5.6.2 on Windows 11
=> Load only binary segmentations

Track/Track.py
This PR makes the following changes:
- By default, display the slice of cine images which pass through the center of mass of the segmentation.
- This behaviour is also replicated when the 'stop' button is pressed
This change was tested using Slicer 5.6.2 on Windows
=> Center Cine Images on Segmentation

Track/Track.py
- Clear the transforms file selector when the reset button is pressed
Tested on Windows with Slicer 5.6.2
=> Clear Transforms File Selector

Track/Track.py, Track/utils/TrackLogic.py
- "Current Alignment" flashing doesn't make sense with 3D image datasets
- "Current Alignment" flashing on playback is distracting, so changed to only show when next/previous buttons are pressed
Tested on Windows 11 using Slicer 5.6.2
=> Change "Current Alignment" Text Flashing

Track/Track.py
- Fix a static mask issue, visible during playback
- Also fix a similar static mask issue that occurs when "Reset All" or "X" buttons are clicked.
Tested on Windows 11 using Slicer 5.6.2
=> Fix Static Mask Bugs

CMakeLists.txt, Track/Track.py, Track/utils/TrackLogic.py
This PR is to fix the current extension to be able to publish on Extension Index. Here is the requirements:
https://github.com/Slicer/ExtensionsIndex/pull/2030#issuecomment-2192631858
Please review!.
=> Update code to move the packages installation until user select + change extension category

Track/Track.py
- Disable column selectors when cine images are playing to avoid the issue where updating the columns during playback would cause the columns to not update.
=> Fix Column Update During Playback

Track/Track.py
This PR fixes the Pause Behaviour to ensure that the buttons aren't disabled when pausing.
Tested on Windows 11 using Slicer 5.6.2
=> Ensure that Pause Behaviour works correctly

Track/Track.py, Track/utils/TrackLogic.py
This change is to support Dicome Files by allow user to select the mask and extract the mask from the dicom files 
automatically. It will only extract the selected mask to save on process time and storage.
Trello
https://trello.com/c/aV2bniwQ/8-high-priority-support-loading-of-dicom-structures-loading-dcm-structure-found-with-folder-dcmstructlung4d
Here is the demo (this is unlisted so only people with the link can view)
https://youtu.be/s9YfhXYzAOs
=> Support dicom files

Track/Track.py
This PR aims to ensure that the 'Translation' column selectors are cleared when the 'Reset All' button is pressed.
Tested on Slicer 5.6.2 using Windows 11
=> Clear Columns on Reset
