Track/Track.py

This PR enables the use of the Stop button during the alignment playback.
It also removes a lot of the commented code, now that our extension has more functionality/stability.
Ubuntu
Windows

[SlicerTrack][Logic] Enable usage of Stop button during playback

---

Track/Track.py

This PR enables the usage of the increment frame (next image) and decrement frame (previous image) buttons.
Ubuntu
Windows

[SlicerTrack][Logic] Enable increment and decrement frame buttons

---

Track/Track.py

The purpose of this PR is to add text in the slice view corner that will make it easier for the user to recognize which image is being aligned to. It will display the text "Pre Alignment" when the image and the overlay has been visualized, but no transformation has been applied. And then it will display "Post Alignment" in the corner when the transformation is applied to align the 3D segmentation to the 2D image.
Note: This text is subject to change if a better suggestion is made.
Note: This PR also fixes a bug where at the pre-alignment step the transformation of the previous image was still being applied to the 3D segmentation. Now there is no transformation and we only see the "default" overlay at the pre-alignment step.
This PR intends to close …

[SlicerTrack][Logic] Display "Pre Alignment" and "Post Alignment" text in slice view corner

---

Track/Track.py

The purpose of this PR is to enable the sequence slider bar so that it moves as we iterate through our images during playback. The sequence label will also display the image number currently being aligned.
Ubuntu
Windows

[SlicerTrack] Implement basic sequence slider visualization

---

Track/Track.py

The purpose of this PR is to implement the 'Cancel' button from the progress dialogues (loading bars) which were recently added.
On cancel, any loaded nodes are removed and the input selector is cleared.
Ubuntu
Windows

[SlicerTrack] Implement 'Cancel' button from images/transforms loading progress dialogue

---

Track/Track.py

The purpose of this PR is to update how we convert the transformation data within SlicerTrack. Previously, we assumed that the conversion information was related to the direction matrix within the metadata of the 2D images (which can be different for a sagittal vs. coronal image). However, it seems that the correct approach is to simply apply a LPS to RAS conversion, since the transformation data was generated outside of 3D Slicer with DICOM images that use the LPS basis, whereas 3D Slicer uses the RAS basis.
Relevant links:
- https://www.slicer.org/wiki/Coordinate_systems#Anatomical_coordinate_system
- https://github.com/Slicer/Slicer/blob/main/Libs/MRML/Core/vtkITKTransformConverter.h#L246
Ubuntu
Windows

[SlicerTrack][Logic] Change how we convert the transformation data so that it can be used in 3D Sllicer

---

Track/Track.py

After some discussion with Dr. Lugez post-IMNO conference we realized we do not want to have the 'pre-alignment' step where the 'default' alignment/overlay of the 3D segmentation over the 2D image is shown. Primarily because it is misleading to the user, but also because it is an unnecessary spec.
Ubuntu
Windows

[SlicerTrack][Logic] Remove the pre-alignment step

---

Track/Track.py

- Remove unused nodes correctly, solving the vtkDebugLeaks issue that was on happening on Windows after using SlicerTrack, then closing 3D Slicer
- Implement custom text on the bottom left corner of enabled slice views (`cornerAnnotation()`), and replace the text from the label ("L:") and background ("B:") layers
- Preserve the texts appearing on the slice views, ("Current Alignment" and `cornerAnnotation()` text) by adding observers, so the text does not change when interacting with the other parts of 3D Slicer.
MacOS (Version 5.3.0 - Preview Release)
Windows (Version 5.3.0 - Preview Release)

Remove unused nodes correctly and preserve slice view text

---

Track/Track.py

fixing image counter so it no longer stops at 99

fix dynamic image counter

---

Track/Track.py

Only support CSV for now. Please file "# TODO" text in the code to add support for txt, xls, xlsx.
Tested on 5.4.0 on MacOS

Add column selector for displacement file

---

Track/Track.py

Description
This change adds the ability to select columns with .xlsx, .txt, and .xls files.
Testing:
Was tested using a windows 11 pc

Add Column Selection support for other file types

---

Track/Track.py

-  The Zoom setting on each Slice View is kept while new images are displayed on 3D Slicer 
- Removed “2D” from “2D Cine Images Folder”
Tested on MacOS (Version 5.4.0 - Stable Release)

Zoom modification on Slice View retained when image is updated

---

Track/Track.py

Description
Change the Default playback speed to 5 fps and max playback speed to 30 fps

Change Default and maximum Playback speeds

---

Track/Track.py

Fix issue the slice view is blank after click apply transformation button.

remove reset visual after click apply transform button

---

Track/utils/TrackLogic.py

-  Updated the message displayed when the cine images are loaded
Tested on Windows (Version 5.6.0 - Stable Release)

Updated message when loading cine images

---

Track/Track.py

Added reset button, to reset module settings back to default values and add any required files.
Also changed the `onPlaybackSpeedChange` method to ensure no errors come up when playback speed is changed.
Tested on Windows (Version 5.6.1)

Add reset button

---

Track/Track.py

This PR intends to make the following changes
- Updated play/pause control button tooltips with unique descriptions
- Tested on Windows (Version 5.6.1 - Stable Release)

 Changed play/pause control button tooltips

---

Track/Track.py

- Removed nonfunctional triangles on the GUI, replaced them with x buttons that allow files to be removed from 3D Slicer
Tested on MacOS (Version 5.6.1 - Stable Release)

Added X buttons for file removal

---

Track/Track.py
Track/utils/TrackLogic.py

- Added support for .nii.gz, .nii, .nhdr, .img, .hdr, and .nrrd image formats/Structures
- Grammatical changes (Translation -> Translations and Apply Transformation: -> Apply Transformations:)

Added More Image and Structure Support

---

Track/Track.py

- Change "Translation" to "Translations" and change "Apply Transformation" to "Apply Transformations"
- Removed .txt from the Transforms File tooltip

Grammer/Tooltip Changes

---

Track/utils/TrackLogic.py

Added Support for 3D Cine Images so they properly display on all slices
Tested on Windows 11, Slicer version 5.6.1

Add support for 3D cine images

---

README.md

remove text of 2D and 3D

---

Track/Track.py
Track/utils/TrackLogic.py

There are 3 big changes in this PR:
- Add correct support for excel file with multiple columns, will pick data base on column selection by user
- Install the python package the first time with Slicer software initialization time.
- Add more tests

Fix: Bug when loading excel files with more than 3 columns

---

Track/Track.py

We will check for Data Availability before running all the tests. If Data is not available, we will display a message and gracefully end the test. If Data is available, we continue to do all the tests.

Update test to check for Data availability

---

CMakeLists.txt
README.md
Track/Track.py

For the purpose of making this extension easy to understand, this pr intends to rename any text containing "SlicerTrack" to "SlicerCineTrack".

Rename SlicerTrack text to SlicerCineTrack

---

.gitignore
README.md

Update link in Read me and .gitignore

Update link in Read me and .gitignore

---

Track/Track.py

- Moved the "Reset All" button down to avoid misclicks between the "Apply Transformations" button

Reset All Location Change

---

Track/Track.py

This PR fixes incorrect centering of 2D images on the segmentation.
Tested on Windows 11 using Slicer 5.6.2

Fix Image Centering Issues

---

Track/Track.py
Track/utils/TrackLogic.py

- Replace the cine image folder selector with a multi cine image file selector

Multi File Selector

---

Track/Track.py

This PR ensures that the testing still works with changes to the UI made in the dev branch
Tested on Slicer 5.6.2 using Windows 11

Ensure testing works with dev branch changes

---

.github/workflows/build-test.yml

In time of PR, will run automated tests

Create automated testing script

---

Track/Track.py

- Sort the list of files that are loaded into the multi-file selector

Sort List of Files

---

Track/utils/TrackLogic.py

- Remove the loading of .img images when loading (.hdr + .img) datasets as .img images are identical to .hdr images

Support Image Format

---

Track/Track.py
Track/utils/TrackLogic.py

- Adds a feature that allows the user to change the colour of the contours

Contour Colour Picker

---

Track/Track.py
Track/utils/TrackLogic.py

- Adds a slider that allows the user to adjust the thickness of the overlay
- Change all instances of "contour" to "overlay"

Overlay Thickness Slider

---

.github/workflows/build-test.yml
CMakeLists.txt
Track/utils/TrackLogic.py

Please test using DICOM dataset (DCM_Struct_Lung4D)
This PR will try to fix cine image orientation if incorrect.
Please watch the demo below.
https://github.com/user-attachments/assets/b186b5b4-9c38-42ce-8a2a-3b545fb6ed64

Fixing image oritation with sitkUtils package

---

Track/Track.py

Skip test if folder doesn't exist

Skip test if folder doesn't exist

---

Track/Track.py

Add code to skip test if can't find data file

Add code to skip test if can't find data file
